# Created by : chilleregeravi
# Email ID: chilleregeravi@gmail.com
# Ant
# Build your NPM Project
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# trigger:
  # - '*'
resources:
  repositories:
    - repository: scrum
      type: git
      name: ScrumProcess/ScrumProcess
      
    - repository: developerexp
      type: github
      endpoint: chilleregeravi
      name:  chilleregeravi/developerxp
      trigger:
        branches:
          include:
            - staging
          exclude:
            - testnewbranch
      
    
      
pr:
  branches:
     include:
       - master
     exclude:
       - staging  

  
pool:
  vmImage: 'vs2017-win2016'
  
steps:
  - checkout: scrum
  - checkout: self  
  
  - task: Npm@1
    displayName: 'NPM BUILD'
    inputs:
      command: install
      workingDir: developerxp-app
  
   
  
