# Created by : chilleregeravi
# Email ID: chilleregeravi@gmail.com
# Ant
# Build your NPM Project
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# trigger:
  # - '*'
trigger:
  branches:
    include:
      - master
    exclude:
      - testnewbranch

resources:
  repositories:
    - repository: developerexp
      type: github
      endpoint: chilleregeravi
      name:  chilleregeravi/developerxp
      
    - repository: scrum
      type: git
      name: ScrumProcess/ScrumProcess  
      
pr:
  branches:
     include:
       - master

  
pool:
  vmImage: 'vs2017-win2016'
  
steps:
  - checkout: self
  - checkout: scrum  
  
  - task: Npm@1
    displayName: 'NPM BUILD'
    inputs:
      command: install
      workingDir: developerxp-app
  
   
  