# Created by : chilleregeravi
# Email ID: chilleregeravi@gmail.com
# Ant
# Build your NPM Project
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# trigger:
  # - '*'
trigger:
  branches:
    include:
      - staging
    exclude:
      - master
        
resources:
  repositories:
    - repository: developerexp
      type: github
      endpoint: chilleregeravi (1)
      name:  chilleregeravi/developerxp
      
pr:
  branches:
     include:
       - master

  
pool:
  name: 'Mine'
  
steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  
  - task: Npm@1
    displayName: 'NPM BUILD'
    inputs:
      command: install
      workingDir: developerxp-app
  
   
  